package org.ftn.constant;

public enum CoordinatorTransactionState {
    STARTED,
    PREPARING,
    ORDER_SERVICE_TRY,
    INVENTORY_SERVICE_TRY,
    PAYMENT_SERVICE_TRY,
    COMMITTING,
    ORDER_SERVICE_COMMIT,
    INVENTORY_SERVICE_COMMIT,
    PAYMENT_SERVICE_COMMIT,
    COMMITTED,
    ABORTING,
    PAYMENT_SERVICE_CANCEL,
    INVENTORY_SERVICE_CANCEL,
    ORDER_SERVICE_CANCEL,
    ABORTED,
    COMMIT_FAILURE,
    ROLLBACK_FAILURE
}
